### ISSUE TITLE
Official icon

### ISSUE THREAD

**Issue by kamsar** [BerserkerDotNet/Unicorn.VisualStudio#2]
If you want, you can grab the official Unicorn icon (v3 has one now!) from http://kamsar.net/nuget/unicorn/logo.png for your use in the VS plugin :)

**Comment by BerserkerDotNet** [comment]
Thank you, I've updated the icon, but there is small issue with a menu.
Is there a chance you can provide me with a 16x16 version of Unicorn logo? Because re-sizing the icon makes it look "blurry". For now I "tweaked" brightness and contrast settings to make it look at least acceptable :)

**Comment by kamsar** [comment]
I've asked our creative guy to make you something :)

**Comment by kamsar** [comment]
It was difficult to get it looking decent at 16x16 so here are two options we came up with; feel free to pick the one that looks best in this case:

![unicorn16](https://cloud.githubusercontent.com/assets/103677/10004135/ffa33576-6064-11e5-90e2-0a9804a24ecb.jpg)
![unicorn16_v2](https://cloud.githubusercontent.com/assets/103677/10004139/024ceb0a-6065-11e5-9f48-19b502b5ed33.jpg)

**Comment by BerserkerDotNet** [comment]
Thank you and creative guy :) "U" version looks better and more prominent than the "Unicorn", on both "Light" and "Dark" themes.
