### ISSUE TITLE
FYI: arbitrary multiple config selection

### ISSUE THREAD

**Issue by kamsar** [BerserkerDotNet/Unicorn.VisualStudio#4]
I'm not sure if this would fit in the plugin, but the latest RC of Unicorn 3 supports syncing and reserializing arbitrary configurations together by passing the `configuration` URL parameter as a caret-delimited list of configurations, for example:

`/unicorn.aspx?verb=Sync&configuration=Test^Other Config^Last Config`

Do with the info as you wish, just thought I'd bring it up. The remote API also supports this.

**Comment by BerserkerDotNet** [comment]
It is really interesting, I did not notice this feature, because I have only one config at my work :)
I've add support for this in version 1.3. It is optional, you can turn it on by goin to settings and selecting "Enable multiple configurations selection"
