### ISSUE TITLE
Configurations dropdown doesn't update after fixing a broken connection

### ISSUE THREAD

**Issue by kamsar** [BerserkerDotNet/Unicorn.VisualStudio#5]
To reproduce:
- Install 1.2.1
- Connect it to something, but use invalid settings. Save the connection anyway.
- The configurations dropdown will show the HTTP response from the broken connection.
- Now edit the connection and fix the settings
- The configuration dropdown remains the invalid HTTP request until visual studio is restarted (after which, it's fixed)

**Comment by BerserkerDotNet** [comment]
Thank you, fixed in version 1.3
