### ISSUE TITLE
Doesn't work with latest version of unicorn 3.02+

### ISSUE THREAD

**Issue by ghost** [BerserkerDotNet/Unicorn.VisualStudio#6]
Get the issues when I use Unicorn 3.02, and your vs extension. 

Here is the stack trace.

Steps to reproduce, 
1. Open Solution that uses a new version of unicorn (Eg. Sitecore Habitat) 
2. Install unicorn.VisualStudio extension
3. Go to /sitecore, and you will be presented with the stack trace below.

I had a quick look at fixing it myself but looks like there has been a significant amount of changes from unicorn 2.0 to 3.0, happy to help you need. 

[TypeLoadException: Method 'Flush' in type 'Unicorn.Remote.Logging.ProgressReporter' from assembly 'Unicorn.Remote, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.]
System.Signature.GetSignature(Void\* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType) +0
System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters() +86
System.Reflection.RuntimeMethodInfo.GetParametersNoCopy() +16
System.RuntimeType.FilterApplyMethodBase(MethodBase methodBase, BindingFlags methodFlags, BindingFlags bindingFlags, CallingConventions callConv, Type[] argumentTypes) +72
System.RuntimeType.GetMethodCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Boolean allowPrefixLookup) +255
System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers) +82
System.Type.GetMethod(String name, BindingFlags bindingAttr, Binder binder, Type[] types, ParameterModifier[] modifiers) +114
Sitecore.Reflection.ReflectionUtil.GetMethod(Object obj, String methodName, Object[] parameters) +58
Sitecore.Pipelines.CoreProcessor.GetMethodInfo(ProcessorObject obj, Object[] parameters) +26
Sitecore.Pipelines.CoreProcessor.GetMethod(Object[] parameters) +159
Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +470
Sitecore.Nexus.Web.HttpModule.��(Object ��, EventArgs ��) +528
System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +142
System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +92

**Comment by BerserkerDotNet** [comment]
Hi

Sorry for a late response.

Unicorn 3+  supports VS extension out of the box, so you don't need any additional DLLs/configs.
If you migrated your solution from 2.0, please make sure you removed any old config files and DLLs. (e.g "Unicorn.Remote.Config.config", "Unicorn.Remote.dll").

Also, in Unicorn 3.0+ remote API is disabled by default, to enable it you have to remove "disabled" part from "Unicorn.Remote.config.disabled" file.

Hope that helps :)
